version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
- package-ecosystem: maven
  directory: "/post-service"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  # Overwrite any ignores created using `@dependabot ignore` commands
  # ignore:
    # Ignore updates to packages that start 'aws'
    # Wildcards match zero or more arbitrary characters
    #- dependency-name: "aws*"
    # Ignore some updates to the 'resteasy' package
    #- dependency-name: "resteasy"
      # Ignore only new versions for 4.x
    #  versions: ["3.x, 4.x"]       
- package-ecosystem: maven
  directory: "/rxjava2"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/rxjava3"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/kotlin"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/kotlin-co"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/post-service-spring"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/post-service-cdi"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10  
- package-ecosystem: maven
  directory: "/mutiny-spring-hibernate"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10   
- package-ecosystem: maven
  directory: "/graphql"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10   
- package-ecosystem: maven
  directory: "/graphql-webclient"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10     
- package-ecosystem: maven
  directory: "/graphql-transport-ws"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10    
